# Generated by Django 5.0.6 on 2026-06-17 17:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='业主姓名')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('id_card', models.CharField(blank=True, max_length=20, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='联系地址')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业主',
                'verbose_name_plural': '业主',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='建筑面积'),
        ),
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='communities.owner'),
        ),
        migrations.AddField(
            model_name='room',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='communities.owner'),
        ),
        migrations.CreateModel(
            name='OwnerChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='变更日期')),
                ('effective_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='生效日期')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='变更原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_changes', to='communities.owner')),
                ('old_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_changes', to='communities.owner')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_changes', to='communities.room')),
            ],
            options={
                'verbose_name': '业主变更记录',
                'verbose_name_plural': '业主变更记录',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
